#!/bin/bash

# Arguments
FILE_01=$1
FILE_02=$2
TRIM_EOF_DURATION=${3:-1.0} # Default is 1.0 second trimmed from EOF

# Prepare variables
BASE_PATH=$(dirname $(readlink -f $FILE_01))
FILENAME_EXT="$(basename "${FILE_01}")"
FILENAME_ONLY="${FILENAME_EXT%.*}"
EXT_ONLY="${FILENAME_EXT#*.}" # Or hardcode it like "mp4"
FILENAME_ONLY_PATH="${BASE_PATH}/${FILENAME_ONLY}"

# Trim EOF duration
INPUT_DURATION=$(ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 "${FILENAME_ONLY}.${EXT_ONLY}")
OUTPUT_DURATION=$(bc <<< "$INPUT_DURATION"-"$TRIM_EOF_DURATION")

echo ffmpeg -y -i "${FILENAME_ONLY}.${EXT_ONLY}" -i "${FILE_02}" -filter_complex "xfade=offset=${OUTPUT_DURATION}:duration=${TRIM_EOF_DURATION};acrossfade=duration=${TRIM_EOF_DURATION}" -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p -q:v 0 "${FILENAME_ONLY}+${FILE_02}"

ffmpeg -y -i "${FILENAME_ONLY}.${EXT_ONLY}" -i "${FILE_02}" -filter_complex "xfade=offset=${OUTPUT_DURATION}:duration=${TRIM_EOF_DURATION};acrossfade=duration=${TRIM_EOF_DURATION}" -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p -q:v 0 "${FILENAME_ONLY}+${FILE_02}"

# rm "${FILE_01}" "${FILE_02}"

# Beeping
echo -e "\a"
sleep 0.3
echo -e "\a"
sleep 0.3
echo -e "\a"
