#!/bin/bash

# Arguments
FILE_RAW=$1

# Prepare variables
BASE_PATH=$(dirname $(readlink -f $FILE_RAW))
FILENAME_EXT="$(basename "${FILE_RAW}")"
FILENAME_ONLY="${FILENAME_EXT%.*}"
EXT_ONLY="${FILENAME_EXT#*.}" # Or hardcode it like "mp4"
FILENAME_ONLY_PATH="${BASE_PATH}/${FILENAME_ONLY}"

ffmpeg -y -i "${FILENAME_ONLY}.${EXT_ONLY}"-c:v copy -filter:a loudnorm -q:v 0 "ln_${FILENAME_ONLY}.${EXT_ONLY}"



# Beeping
echo -e "\a"
sleep 0.3
echo -e "\a"
sleep 0.3
echo -e "\a"
